### ISSUE TITLE
yt:122: = not found

### ISSUE THREAD

**Issue by amaridev** [ddelange/yt#1] opened 2020-04-15 13:50 UTC
Getting this error when calling yt. Dependencies are installed and yt.sh is sourced.

**Comment by ddelange** [comment] 2020-04-15 15:05
hi @amaridev, which OS and bash version are you running? can you try adding the `#!/bin/bash` shebang on line 1 of yt.sh and source again? have a feeling its being interpreted as shell and not bash, but not sure. if that solves it ill add the shebang! (good practise anyway)

**Comment by ddelange** [comment] 2020-04-15 15:17
it might actually also be my Mac's version of bash i tested it on (since i cant reproduce). this line https://github.com/ddelange/yt/blob/e890f597a0be5cabe12c1be2bfa84a2cd9dd962e/yt.sh#L107 could be written as [`declare -a URLS`](http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_10_02.html). 

see also https://stackoverflow.com/a/18921455

let me know if that helps!

**Comment by alebcay** [comment] 2020-05-21 04:42
I'm seeing this issue on macOS Catalina (10.15) running `zsh` 5.8. I tried adding the shebang and re-sourcing and it's still not working. I don't think the shebang will fix it because `zsh` can't delegate to `bash` to source a script like that.

I fixed it by creating a small shim script that fires up bash, `source`s the file, and executes the command with all passed args:
```shell
#!/bin/bash

source ~/.env/yt/yt.sh
yt "$@"
```
I simply placed this somewhere in my path and everything was all set.

**Comment by ddelange** [comment] 2020-05-21 10:16
ah it was zsh! thanks @alebcay, this got me thinking... instead of the wrapper script, shouldnt a shebang `#!/usr/bin/env bash` in yt.sh simply do the trick? have a feeling that will work when just replacing `.bashrc` with `.zshrc` in the installation instructions

**Comment by ddelange** [comment] 2020-05-22 09:19
should be fixed in 214454b8aedb2c6b1cd4a2eb554be438da75cb55 :)

**Closed as completed by ddelange** 2020-05-22 09:19 UTC
